### PR TITLE
Fixed type for errorCauses in OktaApiError

### LINKED ISSUE #374: OktaApiError type doesn't match response from Okta.Client
### Describe the bug?

The `OktaApiError` [type](https://github.com/okta/okta-sdk-nodejs/blob/master/src/types/api-error.d.ts) structure doesn't match the response I'm receiving from the Okta.Client. The `errorCauses` property is currently set as a string, but I am receiving an array of objects.

Example:
If I try to create an oidc application with an existing clientId, I expect an error because clientIds can't be duplicated. I do receive that error
```
{
  status: 400,
  errorCode: 'E0000001',
  errorSummary: 'Api validation failed: client_id',
  errorCauses: [
    {
      errorSummary: 'client_id: An object with this field already exists in the current organization'
    }
  ],
  errorLink: 'E0000001',
  errorId: 'random id',
  url: 'https://my.okta.url/api/v1/apps',
  headers: [Object]
}
```

The error structure for `errorCauses` doesn't match the `OktaApiError` type
```
export declare class OktaApiError extends Error {
  constructor(url: string, status: number, responseBody: Record<string, unknown>, headers: Headers);
  name: string;
  status: number;
  errorCode: string | number;
  errorSummary: string;
  errorCauses: string;
  errorLink: string;
  errorId: string;
  url: string;
  headers: Headers;
  stack: string;
  message: string;
}
```

### What is expected to happen?

I would like to be able to use the `OktaApiError` type to type any errors received from the okta client.

### What is the actual behavior?

I cannot use `OktaApiError` to type errors because `errorCauses` has the wrong type.

### Reproduction Steps?

Make a request the will fail API validation. In my case, I tried to create an Application that doesn't use a unique client_id.

### SDK Versions

"@okta/okta-sdk-nodejs": "6.6.0"

### Execution Environment

nodejs

### Additional Information?

_No response_

### PR DESCRIPTION
**Pull request by denysoblohin-okta**
Type fix: `errorCauses` of `OktaApiError` should have type `{errorSummary: string}[]`, not `string`
https://github.com/okta/okta-sdk-nodejs/pull/397/files#diff-392f545291dc836e0a38e75af8285b4f4bfdcd1477d2570ad54ecaa2032045ed

Resolves #374
Copy of #377
Internal ref: [OKTA-572970](https://oktainc.atlassian.net/browse/OKTA-572970)

### CODE REVIEW

File: src/generated/servers.js [hunk 1]
```diff
@@ -45,23 +48,16 @@ class ServerConfiguration {
...
     return replacedUrl;
   }
-  _encodeParam(val) {
-    return val !== undefined ? encodeURIComponent(val) : undefined;
-  }
   getEndpointUrl(endpoint, vars) {
-    const endpointWithVars = endpoint.replace(/{(\w+)}/g, (match, key) =>
-      this._encodeParam(vars?.[key]) || match
-    );
+    const endpointWithVars = endpoint.replace(/{(\w+)}/g, (match, key) => this._encodeParam(vars?.[key]) || match);
```
Comment (denysoblohin-okta) [inline src/generated/servers.js:52]: Fix linting errors reported during `yarn build:openapi` after PR https://github.com/okta/okta-sdk-nodejs/pull/395

File: test/it/device-api.ts [hunk 2]
```diff
@@ -41,6 +42,7 @@ describe('Device API', () => {
       await client.deviceApi.deactivateDevice({
         deviceId: testDevice.id
       });
+      await utils.delay(1000);
```
Comment (denysoblohin-okta) [inline test/it/device-api.ts:45]: Fix flacky tests

File: scripts/fix-spec.js [hunk 3]
```diff
@@ -20,6 +20,9 @@ function patchSpec3(spec3) {
 
   for (const schemaKey in spec3.components.schemas) {
     const schema = spec3.components.schemas[schemaKey];
+    if (schema.additionalProperties === true) {
```
Comment (denysoblohin-okta) [inline scripts/fix-spec.js:23]: To fix errors during `yarn build:openapi` with latest OpenAPI 3 spec

File: templates/openapi-generator/api/api.mustache [hunk 4]
```diff
@@ -39,7 +39,7 @@ export class {{classname}}RequestFactory extends BaseAPIRequestFactory {
      * {{&summary}}
      {{/summary}}
      {{#allParams}}
-     * @param {{paramName}} {{description}}
+     * @param {{paramName}} {{&description}}
```
Comment (denysoblohin-okta) [inline templates/openapi-generator/api/api.mustache:42]: To prevent unnecessary special characters escaping after running `yarn build:openapi` with latest OpenAPI 3 spec.  (Generated code changes for latest OpenAPI 3 spec will be in new PRs)

**Review by shuowu-okta — APPROVED** [review]
